### ISSUE TITLE
Shortcut keys don't work

### ISSUE THREAD

**Issue by Remiol** [aviaryan/clipjump-addons#2]
Thanks for clipjump, I use it now for over 2 weeks, every day. 
A few things I noted; my shortcuts keys don't work (not even in admin mode).
The clipjump key Ctrl-Shift-A (action window) works fine.
But my own keys do not work, not in the settings menu, not in the ini file (I added windows_copy_shortcut and windows_cut_shortcut key).

Thanks in advance.
Remiol

ps: a wish for the future: a key to delete all current clips (p.e. in the action menu)

**Comment by aviaryan** [comment]
Which OS are you on ? I think you don't have enough disk rights . So the settings are never stored on disk and therefore nothing custom is working. 
Where is clipjump located on the disk ?

**Comment by aviaryan** [comment]
From next time, please use https://github.com/aviaryan/Clipjump for reporting such issues

**Comment by Remiol** [comment]
Yes, you're right!! Thank you aviaryan. Now it works fine. :+1: 

ps: sorry that I didn't post in the correct directory.
