### ISSUE TITLE
Importing Clips to an array of Channels and setting them as FIXED with Specific TAGS

### ISSUE THREAD

**Issue by BrianPassante** [aviaryan/clipjump-addons#5]
(AHK Novice here) Query 1:  Will one of the Plugins aid in building a AHK script that will allow importing a CSV Delimited array of Clips (up 600 total clips) to 15 different channels (while setting the imported Clips as FIXED and Tagging them with preset TAGS?  Will the PUBLIC-API or one of the Custom Plugins assist in such an effort?

Query 2:  What would be the best method using CJ of building a Custom FIXED Clip that has two (interrelated text blocks from the Channel array )blocks of text to be pasted but separated by a TAB or Pause to split the paste into 2 separate fields or text blocks? Maybe delimit the Second part of a Clip with a custom character to allow a script to immediately cut and then repaste the second clip block to the second Area?

Thanks

**Comment by aviaryan** [comment]
Query 1:
I don't think we have such a plugin as of now. But yes, using the API and the plugin architecture, you can create such a plugin.

Query 2:
If you want a single clip to paste 2 strings, I guess you will have to create a plugin which takes the single clip with the multiple blocks of text, parses the clip data, separates the text blocks and then pastes them one by one. This is not that hard to do in AutoHotkey.

**Comment by BrianPassante** [comment]
Thanks for reply!  I'll use your suggestions.  Just didn't want to reinvent the wheel!
